= Neo4j-OGM Spring Data
Michael Simons <michael.simons@neo4j.com>
:doctype: article
:lang: en
:listing-caption: Listing
:source-highlighter: coderay
:icons: font
:latest_version: 1.2.5
:groupId: org.neo4j
:artifactId: neo4j-ogm-spring
:branch: main

[abstract]
--
This is an official fork of https://github.com/spring-projects/spring-data-neo4j/tree/5.3.x[Spring Data Neo4j 5.3.x].
SDN5 is in contrast to SDN6 and higher not an object mapper on its own right, but uses https://github.com/neo4j/neo4j-ogm[Neo4j-OGM] under the hood.
If you are looking for an object mapper with a local (clientside) cache and dirty checking, you are at the right place.
If you are looking for a more record oriented, possible reactive approach and stateless sessions, please use SDN6 or higher.

Neo4j-OGM, this version of SDN as well as SDN6 are fully supported by Neo4j.
--

== Introduction

The fork has no additional functionality but is updated in two dimensions:

* It uses the latest Spring Data Commons and fixes breaking changes that came with it since SDN 5.3.x
* It uses the latest Neo4j-OGM 4.x release and thus is compatible with Neo4j 5.x
* However, Java 17 is required due to the requirements of the latest Neo4j-Java-Driver underpinning Neo4j-OGM 4

NOTE: We restarted the version numbering of this fork at 1.0.0 and removed the tags and branches from the fork. Of course, they will be preserved at https://github.com/spring-projects/spring-data-neo4j/releases[spring-projects/spring-data-neo4j/releases,] and we have no intention to change that.

If you just want to use Neo4j-OGM and SDN5 against Neo4j 4.x over Bolt you can still use the official 5.3.x release.

The coordinates of this SDN versions are:

[source,subs="verbatim,attributes"]
----
{groupId}:{artifactId}-data:{latest_version}
----

The package name has not been changed to avoid issues with existing setups that want to use this fork.

Spring Boot itself does not know about this version of SDN and thus won't autoconfigure it.
We offer a very plain Spring Boot starter mitigating this under the following coordinates:

=== Include in a Maven build

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>{groupId}</groupId>
    <artifactId>{artifactId}-boot-starter</artifactId>
    <version>{latest_version}</version>
</dependency>
----

=== Include in a Gradle build

[source,groovy,subs="verbatim,attributes"]
----
dependencies {
    implementation '{groupId}:{artifactId}-boot-starter:{latest_version}'
}
----

It brings all necessary dependencies.


== License

Spring Data Neo4j is Open Source software released under the https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
We thank the Spring Data Team for not objecting to this friendly fork.
