name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.adoc'
      - 'CONTRIBUTING.adoc'
  pull_request:
    paths-ignore:
      - 'README.adoc'
      - 'CONTRIBUTING.adoc'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set up JDK'
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
        with:
          distribution: zulu
          java-version: 17

      - name: 'Cache Maven packages'
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-${{ github.sha }}

      - name: 'Checkout'
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: 'Clean and verify'
        run: ./mvnw --no-transfer-progress clean verify
